/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AvailabilityResult {
  'date' : string,
  'restaurantId' : RestaurantId,
  'reservedSeats' : bigint,
  'availableSeats' : bigint,
  'timeSlot' : string,
  'totalCapacity' : bigint,
}
export interface AvailabilitySettingsInput {
  'bookingLeadTimeDays' : bigint,
  'maxCoversPerService' : bigint,
  'maxPartySize' : bigint,
  'availableTimeSlots' : Array<string>,
}
export interface AvailabilitySettingsPublic {
  'bookingLeadTimeDays' : bigint,
  'maxCoversPerService' : bigint,
  'maxPartySize' : bigint,
  'restaurantId' : RestaurantId,
  'availableTimeSlots' : Array<string>,
}
export type DayOfWeek = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export type GalleryImageId = bigint;
export interface GalleryImageInput {
  'url' : string,
  'order' : bigint,
  'restaurantId' : RestaurantId,
  'caption' : string,
}
export interface GalleryImagePublic {
  'id' : GalleryImageId,
  'url' : string,
  'order' : bigint,
  'restaurantId' : RestaurantId,
  'caption' : string,
}
export type MenuCategory = { 'dessert' : null } |
  { 'main' : null } |
  { 'appetizer' : null } |
  { 'drink' : null };
export type MenuItemId = bigint;
export interface MenuItemInput {
  'name' : string,
  'description' : string,
  'restaurantId' : RestaurantId,
  'imageUrl' : [] | [string],
  'category' : MenuCategory,
  'price' : number,
}
export interface MenuItemPublic {
  'id' : MenuItemId,
  'name' : string,
  'description' : string,
  'restaurantId' : RestaurantId,
  'imageUrl' : [] | [string],
  'category' : MenuCategory,
  'price' : number,
}
export interface OpeningHours {
  'day' : DayOfWeek,
  'closed' : boolean,
  'close' : string,
  'open' : string,
}
export type PriceRange = { 'one' : null } |
  { 'two' : null } |
  { 'three' : null } |
  { 'four' : null };
export type ReservationId = bigint;
export interface ReservationInput {
  'date' : string,
  'guestCount' : bigint,
  'specialRequests' : string,
  'guestName' : string,
  'guestEmail' : string,
  'restaurantId' : RestaurantId,
  'guestPhone' : string,
  'timeSlot' : string,
}
export interface ReservationPublic {
  'id' : ReservationId,
  'status' : ReservationStatus,
  'bookingReference' : string,
  'date' : string,
  'guestCount' : bigint,
  'specialRequests' : string,
  'createdAt' : Timestamp,
  'guestName' : string,
  'guestEmail' : string,
  'restaurantId' : RestaurantId,
  'guestPhone' : string,
  'timeSlot' : string,
}
export type ReservationStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type RestaurantId = bigint;
export interface RestaurantInput {
  'neighborhood' : string,
  'name' : string,
  'cuisineType' : string,
  'description' : string,
  'email' : string,
  'priceRange' : PriceRange,
  'address' : string,
  'openingHours' : Array<OpeningHours>,
  'phone' : string,
}
export interface RestaurantPublic {
  'id' : RestaurantId,
  'neighborhood' : string,
  'name' : string,
  'cuisineType' : string,
  'description' : string,
  'email' : string,
  'priceRange' : PriceRange,
  'averageRating' : number,
  'address' : string,
  'openingHours' : Array<OpeningHours>,
  'phone' : string,
}
export interface SearchFilter {
  'sortBy' : [] | [SortField],
  'neighborhood' : [] | [string],
  'nameQuery' : [] | [string],
  'cuisineType' : [] | [string],
  'priceRange' : [] | [PriceRange],
}
export type SortField = { 'name' : null } |
  { 'rating' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfilePublic {
  'reservationIds' : Array<ReservationId>,
  'userId' : UserId,
  'favoriteRestaurantIds' : Array<RestaurantId>,
}
export interface _SERVICE {
  'addFavoriteRestaurant' : ActorMethod<[RestaurantId], UserProfilePublic>,
  'addGalleryImage' : ActorMethod<[GalleryImageInput], GalleryImagePublic>,
  'addMenuItem' : ActorMethod<[MenuItemInput], MenuItemPublic>,
  'cancelReservation' : ActorMethod<[ReservationId], [] | [ReservationPublic]>,
  'checkAvailability' : ActorMethod<
    [RestaurantId, string, string],
    AvailabilityResult
  >,
  'confirmReservation' : ActorMethod<[ReservationId], [] | [ReservationPublic]>,
  'createReservation' : ActorMethod<[ReservationInput], ReservationPublic>,
  'createRestaurant' : ActorMethod<[RestaurantInput], RestaurantPublic>,
  'deleteGalleryImage' : ActorMethod<[GalleryImageId], boolean>,
  'deleteMenuItem' : ActorMethod<[MenuItemId], boolean>,
  'getAvailabilitySettings' : ActorMethod<
    [RestaurantId],
    [] | [AvailabilitySettingsPublic]
  >,
  'getGalleryImages' : ActorMethod<[RestaurantId], Array<GalleryImagePublic>>,
  'getMenuItems' : ActorMethod<[RestaurantId], Array<MenuItemPublic>>,
  'getMyProfile' : ActorMethod<[], UserProfilePublic>,
  'getMyReservationHistory' : ActorMethod<[], Array<ReservationPublic>>,
  'getMyReservations' : ActorMethod<[], Array<ReservationPublic>>,
  'getMyRestaurant' : ActorMethod<[], [] | [RestaurantId]>,
  'getReservationByReference' : ActorMethod<[string], [] | [ReservationPublic]>,
  'getReservationsByEmail' : ActorMethod<[string], Array<ReservationPublic>>,
  'getReservationsByRestaurant' : ActorMethod<
    [RestaurantId],
    Array<ReservationPublic>
  >,
  'getRestaurant' : ActorMethod<[RestaurantId], [] | [RestaurantPublic]>,
  'linkAdminToRestaurant' : ActorMethod<[RestaurantId], undefined>,
  'removeFavoriteRestaurant' : ActorMethod<[RestaurantId], UserProfilePublic>,
  'searchRestaurants' : ActorMethod<[SearchFilter], Array<RestaurantPublic>>,
  'updateGalleryImage' : ActorMethod<
    [GalleryImageId, GalleryImageInput],
    [] | [GalleryImagePublic]
  >,
  'updateMenuItem' : ActorMethod<
    [MenuItemId, MenuItemInput],
    [] | [MenuItemPublic]
  >,
  'updateRestaurant' : ActorMethod<
    [RestaurantId, RestaurantInput],
    [] | [RestaurantPublic]
  >,
  'upsertAvailabilitySettings' : ActorMethod<
    [RestaurantId, AvailabilitySettingsInput],
    AvailabilitySettingsPublic
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];