/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RestaurantId = IDL.Nat;
export const ReservationId = IDL.Nat;
export const UserId = IDL.Principal;
export const UserProfilePublic = IDL.Record({
  'reservationIds' : IDL.Vec(ReservationId),
  'userId' : UserId,
  'favoriteRestaurantIds' : IDL.Vec(RestaurantId),
});
export const GalleryImageInput = IDL.Record({
  'url' : IDL.Text,
  'order' : IDL.Nat,
  'restaurantId' : RestaurantId,
  'caption' : IDL.Text,
});
export const GalleryImageId = IDL.Nat;
export const GalleryImagePublic = IDL.Record({
  'id' : GalleryImageId,
  'url' : IDL.Text,
  'order' : IDL.Nat,
  'restaurantId' : RestaurantId,
  'caption' : IDL.Text,
});
export const MenuCategory = IDL.Variant({
  'dessert' : IDL.Null,
  'main' : IDL.Null,
  'appetizer' : IDL.Null,
  'drink' : IDL.Null,
});
export const MenuItemInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'restaurantId' : RestaurantId,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : MenuCategory,
  'price' : IDL.Float64,
});
export const MenuItemId = IDL.Nat;
export const MenuItemPublic = IDL.Record({
  'id' : MenuItemId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'restaurantId' : RestaurantId,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : MenuCategory,
  'price' : IDL.Float64,
});
export const ReservationStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ReservationPublic = IDL.Record({
  'id' : ReservationId,
  'status' : ReservationStatus,
  'bookingReference' : IDL.Text,
  'date' : IDL.Text,
  'guestCount' : IDL.Nat,
  'specialRequests' : IDL.Text,
  'createdAt' : Timestamp,
  'guestName' : IDL.Text,
  'guestEmail' : IDL.Text,
  'restaurantId' : RestaurantId,
  'guestPhone' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const AvailabilityResult = IDL.Record({
  'date' : IDL.Text,
  'restaurantId' : RestaurantId,
  'reservedSeats' : IDL.Nat,
  'availableSeats' : IDL.Nat,
  'timeSlot' : IDL.Text,
  'totalCapacity' : IDL.Nat,
});
export const ReservationInput = IDL.Record({
  'date' : IDL.Text,
  'guestCount' : IDL.Nat,
  'specialRequests' : IDL.Text,
  'guestName' : IDL.Text,
  'guestEmail' : IDL.Text,
  'restaurantId' : RestaurantId,
  'guestPhone' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const PriceRange = IDL.Variant({
  'one' : IDL.Null,
  'two' : IDL.Null,
  'three' : IDL.Null,
  'four' : IDL.Null,
});
export const DayOfWeek = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const OpeningHours = IDL.Record({
  'day' : DayOfWeek,
  'closed' : IDL.Bool,
  'close' : IDL.Text,
  'open' : IDL.Text,
});
export const RestaurantInput = IDL.Record({
  'neighborhood' : IDL.Text,
  'name' : IDL.Text,
  'cuisineType' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'priceRange' : PriceRange,
  'address' : IDL.Text,
  'openingHours' : IDL.Vec(OpeningHours),
  'phone' : IDL.Text,
});
export const RestaurantPublic = IDL.Record({
  'id' : RestaurantId,
  'neighborhood' : IDL.Text,
  'name' : IDL.Text,
  'cuisineType' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'priceRange' : PriceRange,
  'averageRating' : IDL.Float64,
  'address' : IDL.Text,
  'openingHours' : IDL.Vec(OpeningHours),
  'phone' : IDL.Text,
});
export const AvailabilitySettingsPublic = IDL.Record({
  'bookingLeadTimeDays' : IDL.Nat,
  'maxCoversPerService' : IDL.Nat,
  'maxPartySize' : IDL.Nat,
  'restaurantId' : RestaurantId,
  'availableTimeSlots' : IDL.Vec(IDL.Text),
});
export const SortField = IDL.Variant({
  'name' : IDL.Null,
  'rating' : IDL.Null,
});
export const SearchFilter = IDL.Record({
  'sortBy' : IDL.Opt(SortField),
  'neighborhood' : IDL.Opt(IDL.Text),
  'nameQuery' : IDL.Opt(IDL.Text),
  'cuisineType' : IDL.Opt(IDL.Text),
  'priceRange' : IDL.Opt(PriceRange),
});
export const AvailabilitySettingsInput = IDL.Record({
  'bookingLeadTimeDays' : IDL.Nat,
  'maxCoversPerService' : IDL.Nat,
  'maxPartySize' : IDL.Nat,
  'availableTimeSlots' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addFavoriteRestaurant' : IDL.Func([RestaurantId], [UserProfilePublic], []),
  'addGalleryImage' : IDL.Func([GalleryImageInput], [GalleryImagePublic], []),
  'addMenuItem' : IDL.Func([MenuItemInput], [MenuItemPublic], []),
  'cancelReservation' : IDL.Func(
      [ReservationId],
      [IDL.Opt(ReservationPublic)],
      [],
    ),
  'checkAvailability' : IDL.Func(
      [RestaurantId, IDL.Text, IDL.Text],
      [AvailabilityResult],
      ['query'],
    ),
  'confirmReservation' : IDL.Func(
      [ReservationId],
      [IDL.Opt(ReservationPublic)],
      [],
    ),
  'createReservation' : IDL.Func([ReservationInput], [ReservationPublic], []),
  'createRestaurant' : IDL.Func([RestaurantInput], [RestaurantPublic], []),
  'deleteGalleryImage' : IDL.Func([GalleryImageId], [IDL.Bool], []),
  'deleteMenuItem' : IDL.Func([MenuItemId], [IDL.Bool], []),
  'getAvailabilitySettings' : IDL.Func(
      [RestaurantId],
      [IDL.Opt(AvailabilitySettingsPublic)],
      ['query'],
    ),
  'getGalleryImages' : IDL.Func(
      [RestaurantId],
      [IDL.Vec(GalleryImagePublic)],
      ['query'],
    ),
  'getMenuItems' : IDL.Func(
      [RestaurantId],
      [IDL.Vec(MenuItemPublic)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [UserProfilePublic], ['query']),
  'getMyReservationHistory' : IDL.Func(
      [],
      [IDL.Vec(ReservationPublic)],
      ['query'],
    ),
  'getMyReservations' : IDL.Func([], [IDL.Vec(ReservationPublic)], ['query']),
  'getMyRestaurant' : IDL.Func([], [IDL.Opt(RestaurantId)], ['query']),
  'getReservationByReference' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ReservationPublic)],
      ['query'],
    ),
  'getReservationsByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ReservationPublic)],
      ['query'],
    ),
  'getReservationsByRestaurant' : IDL.Func(
      [RestaurantId],
      [IDL.Vec(ReservationPublic)],
      ['query'],
    ),
  'getRestaurant' : IDL.Func(
      [RestaurantId],
      [IDL.Opt(RestaurantPublic)],
      ['query'],
    ),
  'linkAdminToRestaurant' : IDL.Func([RestaurantId], [], []),
  'removeFavoriteRestaurant' : IDL.Func(
      [RestaurantId],
      [UserProfilePublic],
      [],
    ),
  'searchRestaurants' : IDL.Func(
      [SearchFilter],
      [IDL.Vec(RestaurantPublic)],
      ['query'],
    ),
  'updateGalleryImage' : IDL.Func(
      [GalleryImageId, GalleryImageInput],
      [IDL.Opt(GalleryImagePublic)],
      [],
    ),
  'updateMenuItem' : IDL.Func(
      [MenuItemId, MenuItemInput],
      [IDL.Opt(MenuItemPublic)],
      [],
    ),
  'updateRestaurant' : IDL.Func(
      [RestaurantId, RestaurantInput],
      [IDL.Opt(RestaurantPublic)],
      [],
    ),
  'upsertAvailabilitySettings' : IDL.Func(
      [RestaurantId, AvailabilitySettingsInput],
      [AvailabilitySettingsPublic],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RestaurantId = IDL.Nat;
  const ReservationId = IDL.Nat;
  const UserId = IDL.Principal;
  const UserProfilePublic = IDL.Record({
    'reservationIds' : IDL.Vec(ReservationId),
    'userId' : UserId,
    'favoriteRestaurantIds' : IDL.Vec(RestaurantId),
  });
  const GalleryImageInput = IDL.Record({
    'url' : IDL.Text,
    'order' : IDL.Nat,
    'restaurantId' : RestaurantId,
    'caption' : IDL.Text,
  });
  const GalleryImageId = IDL.Nat;
  const GalleryImagePublic = IDL.Record({
    'id' : GalleryImageId,
    'url' : IDL.Text,
    'order' : IDL.Nat,
    'restaurantId' : RestaurantId,
    'caption' : IDL.Text,
  });
  const MenuCategory = IDL.Variant({
    'dessert' : IDL.Null,
    'main' : IDL.Null,
    'appetizer' : IDL.Null,
    'drink' : IDL.Null,
  });
  const MenuItemInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'restaurantId' : RestaurantId,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : MenuCategory,
    'price' : IDL.Float64,
  });
  const MenuItemId = IDL.Nat;
  const MenuItemPublic = IDL.Record({
    'id' : MenuItemId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'restaurantId' : RestaurantId,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : MenuCategory,
    'price' : IDL.Float64,
  });
  const ReservationStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ReservationPublic = IDL.Record({
    'id' : ReservationId,
    'status' : ReservationStatus,
    'bookingReference' : IDL.Text,
    'date' : IDL.Text,
    'guestCount' : IDL.Nat,
    'specialRequests' : IDL.Text,
    'createdAt' : Timestamp,
    'guestName' : IDL.Text,
    'guestEmail' : IDL.Text,
    'restaurantId' : RestaurantId,
    'guestPhone' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const AvailabilityResult = IDL.Record({
    'date' : IDL.Text,
    'restaurantId' : RestaurantId,
    'reservedSeats' : IDL.Nat,
    'availableSeats' : IDL.Nat,
    'timeSlot' : IDL.Text,
    'totalCapacity' : IDL.Nat,
  });
  const ReservationInput = IDL.Record({
    'date' : IDL.Text,
    'guestCount' : IDL.Nat,
    'specialRequests' : IDL.Text,
    'guestName' : IDL.Text,
    'guestEmail' : IDL.Text,
    'restaurantId' : RestaurantId,
    'guestPhone' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const PriceRange = IDL.Variant({
    'one' : IDL.Null,
    'two' : IDL.Null,
    'three' : IDL.Null,
    'four' : IDL.Null,
  });
  const DayOfWeek = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const OpeningHours = IDL.Record({
    'day' : DayOfWeek,
    'closed' : IDL.Bool,
    'close' : IDL.Text,
    'open' : IDL.Text,
  });
  const RestaurantInput = IDL.Record({
    'neighborhood' : IDL.Text,
    'name' : IDL.Text,
    'cuisineType' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'priceRange' : PriceRange,
    'address' : IDL.Text,
    'openingHours' : IDL.Vec(OpeningHours),
    'phone' : IDL.Text,
  });
  const RestaurantPublic = IDL.Record({
    'id' : RestaurantId,
    'neighborhood' : IDL.Text,
    'name' : IDL.Text,
    'cuisineType' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'priceRange' : PriceRange,
    'averageRating' : IDL.Float64,
    'address' : IDL.Text,
    'openingHours' : IDL.Vec(OpeningHours),
    'phone' : IDL.Text,
  });
  const AvailabilitySettingsPublic = IDL.Record({
    'bookingLeadTimeDays' : IDL.Nat,
    'maxCoversPerService' : IDL.Nat,
    'maxPartySize' : IDL.Nat,
    'restaurantId' : RestaurantId,
    'availableTimeSlots' : IDL.Vec(IDL.Text),
  });
  const SortField = IDL.Variant({ 'name' : IDL.Null, 'rating' : IDL.Null });
  const SearchFilter = IDL.Record({
    'sortBy' : IDL.Opt(SortField),
    'neighborhood' : IDL.Opt(IDL.Text),
    'nameQuery' : IDL.Opt(IDL.Text),
    'cuisineType' : IDL.Opt(IDL.Text),
    'priceRange' : IDL.Opt(PriceRange),
  });
  const AvailabilitySettingsInput = IDL.Record({
    'bookingLeadTimeDays' : IDL.Nat,
    'maxCoversPerService' : IDL.Nat,
    'maxPartySize' : IDL.Nat,
    'availableTimeSlots' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addFavoriteRestaurant' : IDL.Func([RestaurantId], [UserProfilePublic], []),
    'addGalleryImage' : IDL.Func([GalleryImageInput], [GalleryImagePublic], []),
    'addMenuItem' : IDL.Func([MenuItemInput], [MenuItemPublic], []),
    'cancelReservation' : IDL.Func(
        [ReservationId],
        [IDL.Opt(ReservationPublic)],
        [],
      ),
    'checkAvailability' : IDL.Func(
        [RestaurantId, IDL.Text, IDL.Text],
        [AvailabilityResult],
        ['query'],
      ),
    'confirmReservation' : IDL.Func(
        [ReservationId],
        [IDL.Opt(ReservationPublic)],
        [],
      ),
    'createReservation' : IDL.Func([ReservationInput], [ReservationPublic], []),
    'createRestaurant' : IDL.Func([RestaurantInput], [RestaurantPublic], []),
    'deleteGalleryImage' : IDL.Func([GalleryImageId], [IDL.Bool], []),
    'deleteMenuItem' : IDL.Func([MenuItemId], [IDL.Bool], []),
    'getAvailabilitySettings' : IDL.Func(
        [RestaurantId],
        [IDL.Opt(AvailabilitySettingsPublic)],
        ['query'],
      ),
    'getGalleryImages' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(GalleryImagePublic)],
        ['query'],
      ),
    'getMenuItems' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(MenuItemPublic)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [UserProfilePublic], ['query']),
    'getMyReservationHistory' : IDL.Func(
        [],
        [IDL.Vec(ReservationPublic)],
        ['query'],
      ),
    'getMyReservations' : IDL.Func([], [IDL.Vec(ReservationPublic)], ['query']),
    'getMyRestaurant' : IDL.Func([], [IDL.Opt(RestaurantId)], ['query']),
    'getReservationByReference' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ReservationPublic)],
        ['query'],
      ),
    'getReservationsByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ReservationPublic)],
        ['query'],
      ),
    'getReservationsByRestaurant' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(ReservationPublic)],
        ['query'],
      ),
    'getRestaurant' : IDL.Func(
        [RestaurantId],
        [IDL.Opt(RestaurantPublic)],
        ['query'],
      ),
    'linkAdminToRestaurant' : IDL.Func([RestaurantId], [], []),
    'removeFavoriteRestaurant' : IDL.Func(
        [RestaurantId],
        [UserProfilePublic],
        [],
      ),
    'searchRestaurants' : IDL.Func(
        [SearchFilter],
        [IDL.Vec(RestaurantPublic)],
        ['query'],
      ),
    'updateGalleryImage' : IDL.Func(
        [GalleryImageId, GalleryImageInput],
        [IDL.Opt(GalleryImagePublic)],
        [],
      ),
    'updateMenuItem' : IDL.Func(
        [MenuItemId, MenuItemInput],
        [IDL.Opt(MenuItemPublic)],
        [],
      ),
    'updateRestaurant' : IDL.Func(
        [RestaurantId, RestaurantInput],
        [IDL.Opt(RestaurantPublic)],
        [],
      ),
    'upsertAvailabilitySettings' : IDL.Func(
        [RestaurantId, AvailabilitySettingsInput],
        [AvailabilitySettingsPublic],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };