/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface RestaurantPublic {
    id: RestaurantId;
    neighborhood: string;
    name: string;
    cuisineType: string;
    description: string;
    email: string;
    priceRange: PriceRange;
    averageRating: number;
    address: string;
    openingHours: Array<OpeningHours>;
    phone: string;
}
export interface SearchFilter {
    sortBy?: SortField;
    neighborhood?: string;
    nameQuery?: string;
    cuisineType?: string;
    priceRange?: PriceRange;
}
export interface AvailabilitySettingsPublic {
    bookingLeadTimeDays: bigint;
    maxCoversPerService: bigint;
    maxPartySize: bigint;
    restaurantId: RestaurantId;
    availableTimeSlots: Array<string>;
}
export interface ReservationPublic {
    id: ReservationId;
    status: ReservationStatus;
    bookingReference: string;
    date: string;
    guestCount: bigint;
    specialRequests: string;
    createdAt: Timestamp;
    guestName: string;
    guestEmail: string;
    restaurantId: RestaurantId;
    guestPhone: string;
    timeSlot: string;
}
export interface RestaurantInput {
    neighborhood: string;
    name: string;
    cuisineType: string;
    description: string;
    email: string;
    priceRange: PriceRange;
    address: string;
    openingHours: Array<OpeningHours>;
    phone: string;
}
export type RestaurantId = bigint;
export type ReservationId = bigint;
export interface UserProfilePublic {
    reservationIds: Array<ReservationId>;
    userId: UserId;
    favoriteRestaurantIds: Array<RestaurantId>;
}
export interface MenuItemInput {
    name: string;
    description: string;
    restaurantId: RestaurantId;
    imageUrl?: string;
    category: MenuCategory;
    price: number;
}
export type UserId = Principal;
export interface OpeningHours {
    day: DayOfWeek;
    closed: boolean;
    close: string;
    open: string;
}
export type MenuItemId = bigint;
export interface GalleryImagePublic {
    id: GalleryImageId;
    url: string;
    order: bigint;
    restaurantId: RestaurantId;
    caption: string;
}
export type GalleryImageId = bigint;
export interface AvailabilitySettingsInput {
    bookingLeadTimeDays: bigint;
    maxCoversPerService: bigint;
    maxPartySize: bigint;
    availableTimeSlots: Array<string>;
}
export interface AvailabilityResult {
    date: string;
    restaurantId: RestaurantId;
    reservedSeats: bigint;
    availableSeats: bigint;
    timeSlot: string;
    totalCapacity: bigint;
}
export interface MenuItemPublic {
    id: MenuItemId;
    name: string;
    description: string;
    restaurantId: RestaurantId;
    imageUrl?: string;
    category: MenuCategory;
    price: number;
}
export interface GalleryImageInput {
    url: string;
    order: bigint;
    restaurantId: RestaurantId;
    caption: string;
}
export interface ReservationInput {
    date: string;
    guestCount: bigint;
    specialRequests: string;
    guestName: string;
    guestEmail: string;
    restaurantId: RestaurantId;
    guestPhone: string;
    timeSlot: string;
}
export enum DayOfWeek {
    tuesday = "tuesday",
    wednesday = "wednesday",
    saturday = "saturday",
    thursday = "thursday",
    sunday = "sunday",
    friday = "friday",
    monday = "monday"
}
export enum MenuCategory {
    dessert = "dessert",
    main = "main",
    appetizer = "appetizer",
    drink = "drink"
}
export enum PriceRange {
    one = "one",
    two = "two",
    three = "three",
    four = "four"
}
export enum ReservationStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum SortField {
    name = "name",
    rating = "rating"
}
export interface backendInterface {
    addFavoriteRestaurant(restaurantId: RestaurantId): Promise<UserProfilePublic>;
    addGalleryImage(input: GalleryImageInput): Promise<GalleryImagePublic>;
    addMenuItem(input: MenuItemInput): Promise<MenuItemPublic>;
    cancelReservation(id: ReservationId): Promise<ReservationPublic | null>;
    checkAvailability(restaurantId: RestaurantId, date: string, timeSlot: string): Promise<AvailabilityResult>;
    confirmReservation(id: ReservationId): Promise<ReservationPublic | null>;
    createReservation(input: ReservationInput): Promise<ReservationPublic>;
    createRestaurant(input: RestaurantInput): Promise<RestaurantPublic>;
    deleteGalleryImage(id: GalleryImageId): Promise<boolean>;
    deleteMenuItem(id: MenuItemId): Promise<boolean>;
    getAvailabilitySettings(restaurantId: RestaurantId): Promise<AvailabilitySettingsPublic | null>;
    getGalleryImages(restaurantId: RestaurantId): Promise<Array<GalleryImagePublic>>;
    getMenuItems(restaurantId: RestaurantId): Promise<Array<MenuItemPublic>>;
    getMyProfile(): Promise<UserProfilePublic>;
    getMyReservationHistory(): Promise<Array<ReservationPublic>>;
    getMyReservations(): Promise<Array<ReservationPublic>>;
    getMyRestaurant(): Promise<RestaurantId | null>;
    getReservationByReference(bookingReference: string): Promise<ReservationPublic | null>;
    getReservationsByEmail(email: string): Promise<Array<ReservationPublic>>;
    getReservationsByRestaurant(restaurantId: RestaurantId): Promise<Array<ReservationPublic>>;
    getRestaurant(id: RestaurantId): Promise<RestaurantPublic | null>;
    linkAdminToRestaurant(restaurantId: RestaurantId): Promise<void>;
    removeFavoriteRestaurant(restaurantId: RestaurantId): Promise<UserProfilePublic>;
    searchRestaurants(filter: SearchFilter): Promise<Array<RestaurantPublic>>;
    updateGalleryImage(id: GalleryImageId, input: GalleryImageInput): Promise<GalleryImagePublic | null>;
    updateMenuItem(id: MenuItemId, input: MenuItemInput): Promise<MenuItemPublic | null>;
    updateRestaurant(id: RestaurantId, input: RestaurantInput): Promise<RestaurantPublic | null>;
    upsertAvailabilitySettings(restaurantId: RestaurantId, input: AvailabilitySettingsInput): Promise<AvailabilitySettingsPublic>;
}
import type { AvailabilitySettingsPublic as _AvailabilitySettingsPublic, DayOfWeek as _DayOfWeek, GalleryImagePublic as _GalleryImagePublic, MenuCategory as _MenuCategory, MenuItemId as _MenuItemId, MenuItemInput as _MenuItemInput, MenuItemPublic as _MenuItemPublic, OpeningHours as _OpeningHours, PriceRange as _PriceRange, ReservationId as _ReservationId, ReservationPublic as _ReservationPublic, ReservationStatus as _ReservationStatus, RestaurantId as _RestaurantId, RestaurantInput as _RestaurantInput, RestaurantPublic as _RestaurantPublic, SearchFilter as _SearchFilter, SortField as _SortField, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFavoriteRestaurant(arg0: RestaurantId): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavoriteRestaurant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavoriteRestaurant(arg0);
            return result;
        }
    }
    async addGalleryImage(arg0: GalleryImageInput): Promise<GalleryImagePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryImage(arg0);
            return result;
        }
    }
    async addMenuItem(arg0: MenuItemInput): Promise<MenuItemPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(to_candid_MenuItemInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_MenuItemPublic_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(to_candid_MenuItemInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_MenuItemPublic_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelReservation(arg0: ReservationId): Promise<ReservationPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelReservation(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelReservation(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkAvailability(arg0: RestaurantId, arg1: string, arg2: string): Promise<AvailabilityResult> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAvailability(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAvailability(arg0, arg1, arg2);
            return result;
        }
    }
    async confirmReservation(arg0: ReservationId): Promise<ReservationPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmReservation(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmReservation(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReservation(arg0: ReservationInput): Promise<ReservationPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createReservation(arg0);
                return from_candid_ReservationPublic_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReservation(arg0);
            return from_candid_ReservationPublic_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRestaurant(arg0: RestaurantInput): Promise<RestaurantPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createRestaurant(to_candid_RestaurantInput_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RestaurantPublic_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRestaurant(to_candid_RestaurantInput_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RestaurantPublic_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteGalleryImage(arg0: GalleryImageId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryImage(arg0);
            return result;
        }
    }
    async deleteMenuItem(arg0: MenuItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async getAvailabilitySettings(arg0: RestaurantId): Promise<AvailabilitySettingsPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailabilitySettings(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailabilitySettings(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryImages(arg0: RestaurantId): Promise<Array<GalleryImagePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImages(arg0);
            return result;
        }
    }
    async getMenuItems(arg0: RestaurantId): Promise<Array<MenuItemPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItems(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItems(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return result;
        }
    }
    async getMyReservationHistory(): Promise<Array<ReservationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReservationHistory();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReservationHistory();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReservations(): Promise<Array<ReservationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReservations();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReservations();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRestaurant(): Promise<RestaurantId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRestaurant();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRestaurant();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReservationByReference(arg0: string): Promise<ReservationPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReservationByReference(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReservationByReference(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReservationsByEmail(arg0: string): Promise<Array<ReservationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReservationsByEmail(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReservationsByEmail(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReservationsByRestaurant(arg0: RestaurantId): Promise<Array<ReservationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReservationsByRestaurant(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReservationsByRestaurant(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurant(arg0: RestaurantId): Promise<RestaurantPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurant(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurant(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async linkAdminToRestaurant(arg0: RestaurantId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkAdminToRestaurant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkAdminToRestaurant(arg0);
            return result;
        }
    }
    async removeFavoriteRestaurant(arg0: RestaurantId): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavoriteRestaurant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavoriteRestaurant(arg0);
            return result;
        }
    }
    async searchRestaurants(arg0: SearchFilter): Promise<Array<RestaurantPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRestaurants(to_candid_SearchFilter_n38(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRestaurants(to_candid_SearchFilter_n38(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGalleryImage(arg0: GalleryImageId, arg1: GalleryImageInput): Promise<GalleryImagePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryImage(arg0, arg1);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryImage(arg0, arg1);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMenuItem(arg0: MenuItemId, arg1: MenuItemInput): Promise<MenuItemPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, to_candid_MenuItemInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, to_candid_MenuItemInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRestaurant(arg0: RestaurantId, arg1: RestaurantInput): Promise<RestaurantPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRestaurant(arg0, to_candid_RestaurantInput_n15(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRestaurant(arg0, to_candid_RestaurantInput_n15(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertAvailabilitySettings(arg0: RestaurantId, arg1: AvailabilitySettingsInput): Promise<AvailabilitySettingsPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertAvailabilitySettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertAvailabilitySettings(arg0, arg1);
            return result;
        }
    }
}
function from_candid_DayOfWeek_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayOfWeek): DayOfWeek {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_MenuCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuCategory): MenuCategory {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_MenuItemPublic_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItemPublic): MenuItemPublic {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_OpeningHours_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OpeningHours): OpeningHours {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_PriceRange_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceRange): PriceRange {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ReservationPublic_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReservationPublic): ReservationPublic {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ReservationStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReservationStatus): ReservationStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_RestaurantPublic_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RestaurantPublic): RestaurantPublic {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReservationPublic]): ReservationPublic | null {
    return value.length === 0 ? null : from_candid_ReservationPublic_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AvailabilitySettingsPublic]): AvailabilitySettingsPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantId]): RestaurantId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantPublic]): RestaurantPublic | null {
    return value.length === 0 ? null : from_candid_RestaurantPublic_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GalleryImagePublic]): GalleryImagePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItemPublic]): MenuItemPublic | null {
    return value.length === 0 ? null : from_candid_MenuItemPublic_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReservationId;
    status: _ReservationStatus;
    bookingReference: string;
    date: string;
    guestCount: bigint;
    specialRequests: string;
    createdAt: _Timestamp;
    guestName: string;
    guestEmail: string;
    restaurantId: _RestaurantId;
    guestPhone: string;
    timeSlot: string;
}): {
    id: ReservationId;
    status: ReservationStatus;
    bookingReference: string;
    date: string;
    guestCount: bigint;
    specialRequests: string;
    createdAt: Timestamp;
    guestName: string;
    guestEmail: string;
    restaurantId: RestaurantId;
    guestPhone: string;
    timeSlot: string;
} {
    return {
        id: value.id,
        status: from_candid_ReservationStatus_n13(_uploadFile, _downloadFile, value.status),
        bookingReference: value.bookingReference,
        date: value.date,
        guestCount: value.guestCount,
        specialRequests: value.specialRequests,
        createdAt: value.createdAt,
        guestName: value.guestName,
        guestEmail: value.guestEmail,
        restaurantId: value.restaurantId,
        guestPhone: value.guestPhone,
        timeSlot: value.timeSlot
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RestaurantId;
    neighborhood: string;
    name: string;
    cuisineType: string;
    description: string;
    email: string;
    priceRange: _PriceRange;
    averageRating: number;
    address: string;
    openingHours: Array<_OpeningHours>;
    phone: string;
}): {
    id: RestaurantId;
    neighborhood: string;
    name: string;
    cuisineType: string;
    description: string;
    email: string;
    priceRange: PriceRange;
    averageRating: number;
    address: string;
    openingHours: Array<OpeningHours>;
    phone: string;
} {
    return {
        id: value.id,
        neighborhood: value.neighborhood,
        name: value.name,
        cuisineType: value.cuisineType,
        description: value.description,
        email: value.email,
        priceRange: from_candid_PriceRange_n26(_uploadFile, _downloadFile, value.priceRange),
        averageRating: value.averageRating,
        address: value.address,
        openingHours: from_candid_vec_n28(_uploadFile, _downloadFile, value.openingHours),
        phone: value.phone
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: _DayOfWeek;
    closed: boolean;
    close: string;
    open: string;
}): {
    day: DayOfWeek;
    closed: boolean;
    close: string;
    open: string;
} {
    return {
        day: from_candid_DayOfWeek_n31(_uploadFile, _downloadFile, value.day),
        closed: value.closed,
        close: value.close,
        open: value.open
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MenuItemId;
    name: string;
    description: string;
    restaurantId: _RestaurantId;
    imageUrl: [] | [string];
    category: _MenuCategory;
    price: number;
}): {
    id: MenuItemId;
    name: string;
    description: string;
    restaurantId: RestaurantId;
    imageUrl?: string;
    category: MenuCategory;
    price: number;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        restaurantId: value.restaurantId,
        imageUrl: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.imageUrl)),
        category: from_candid_MenuCategory_n8(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): ReservationStatus {
    return "cancelled" in value ? ReservationStatus.cancelled : "pending" in value ? ReservationStatus.pending : "confirmed" in value ? ReservationStatus.confirmed : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    one: null;
} | {
    two: null;
} | {
    three: null;
} | {
    four: null;
}): PriceRange {
    return "one" in value ? PriceRange.one : "two" in value ? PriceRange.two : "three" in value ? PriceRange.three : "four" in value ? PriceRange.four : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
}): DayOfWeek {
    return "tuesday" in value ? DayOfWeek.tuesday : "wednesday" in value ? DayOfWeek.wednesday : "saturday" in value ? DayOfWeek.saturday : "thursday" in value ? DayOfWeek.thursday : "sunday" in value ? DayOfWeek.sunday : "friday" in value ? DayOfWeek.friday : "monday" in value ? DayOfWeek.monday : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dessert: null;
} | {
    main: null;
} | {
    appetizer: null;
} | {
    drink: null;
}): MenuCategory {
    return "dessert" in value ? MenuCategory.dessert : "main" in value ? MenuCategory.main : "appetizer" in value ? MenuCategory.appetizer : "drink" in value ? MenuCategory.drink : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OpeningHours>): Array<OpeningHours> {
    return value.map((x)=>from_candid_OpeningHours_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItemPublic>): Array<MenuItemPublic> {
    return value.map((x)=>from_candid_MenuItemPublic_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReservationPublic>): Array<ReservationPublic> {
    return value.map((x)=>from_candid_ReservationPublic_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RestaurantPublic>): Array<RestaurantPublic> {
    return value.map((x)=>from_candid_RestaurantPublic_n24(_uploadFile, _downloadFile, x));
}
function to_candid_DayOfWeek_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): _DayOfWeek {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_MenuCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuCategory): _MenuCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_MenuItemInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItemInput): _MenuItemInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_OpeningHours_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OpeningHours): _OpeningHours {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_PriceRange_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceRange): _PriceRange {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_RestaurantInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantInput): _RestaurantInput {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_SearchFilter_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchFilter): _SearchFilter {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_SortField_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortField): _SortField {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    neighborhood: string;
    name: string;
    cuisineType: string;
    description: string;
    email: string;
    priceRange: PriceRange;
    address: string;
    openingHours: Array<OpeningHours>;
    phone: string;
}): {
    neighborhood: string;
    name: string;
    cuisineType: string;
    description: string;
    email: string;
    priceRange: _PriceRange;
    address: string;
    openingHours: Array<_OpeningHours>;
    phone: string;
} {
    return {
        neighborhood: value.neighborhood,
        name: value.name,
        cuisineType: value.cuisineType,
        description: value.description,
        email: value.email,
        priceRange: to_candid_PriceRange_n17(_uploadFile, _downloadFile, value.priceRange),
        address: value.address,
        openingHours: to_candid_vec_n19(_uploadFile, _downloadFile, value.openingHours),
        phone: value.phone
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    restaurantId: RestaurantId;
    imageUrl?: string;
    category: MenuCategory;
    price: number;
}): {
    name: string;
    description: string;
    restaurantId: _RestaurantId;
    imageUrl: [] | [string];
    category: _MenuCategory;
    price: number;
} {
    return {
        name: value.name,
        description: value.description,
        restaurantId: value.restaurantId,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        category: to_candid_MenuCategory_n3(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: DayOfWeek;
    closed: boolean;
    close: string;
    open: string;
}): {
    day: _DayOfWeek;
    closed: boolean;
    close: string;
    open: string;
} {
    return {
        day: to_candid_DayOfWeek_n22(_uploadFile, _downloadFile, value.day),
        closed: value.closed,
        close: value.close,
        open: value.open
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortBy?: SortField;
    neighborhood?: string;
    nameQuery?: string;
    cuisineType?: string;
    priceRange?: PriceRange;
}): {
    sortBy: [] | [_SortField];
    neighborhood: [] | [string];
    nameQuery: [] | [string];
    cuisineType: [] | [string];
    priceRange: [] | [_PriceRange];
} {
    return {
        sortBy: value.sortBy ? candid_some(to_candid_SortField_n40(_uploadFile, _downloadFile, value.sortBy)) : candid_none(),
        neighborhood: value.neighborhood ? candid_some(value.neighborhood) : candid_none(),
        nameQuery: value.nameQuery ? candid_some(value.nameQuery) : candid_none(),
        cuisineType: value.cuisineType ? candid_some(value.cuisineType) : candid_none(),
        priceRange: value.priceRange ? candid_some(to_candid_PriceRange_n17(_uploadFile, _downloadFile, value.priceRange)) : candid_none()
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceRange): {
    one: null;
} | {
    two: null;
} | {
    three: null;
} | {
    four: null;
} {
    return value == PriceRange.one ? {
        one: null
    } : value == PriceRange.two ? {
        two: null
    } : value == PriceRange.three ? {
        three: null
    } : value == PriceRange.four ? {
        four: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
} {
    return value == DayOfWeek.tuesday ? {
        tuesday: null
    } : value == DayOfWeek.wednesday ? {
        wednesday: null
    } : value == DayOfWeek.saturday ? {
        saturday: null
    } : value == DayOfWeek.thursday ? {
        thursday: null
    } : value == DayOfWeek.sunday ? {
        sunday: null
    } : value == DayOfWeek.friday ? {
        friday: null
    } : value == DayOfWeek.monday ? {
        monday: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuCategory): {
    dessert: null;
} | {
    main: null;
} | {
    appetizer: null;
} | {
    drink: null;
} {
    return value == MenuCategory.dessert ? {
        dessert: null
    } : value == MenuCategory.main ? {
        main: null
    } : value == MenuCategory.appetizer ? {
        appetizer: null
    } : value == MenuCategory.drink ? {
        drink: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortField): {
    name: null;
} | {
    rating: null;
} {
    return value == SortField.name ? {
        name: null
    } : value == SortField.rating ? {
        rating: null
    } : value;
}
function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OpeningHours>): Array<_OpeningHours> {
    return value.map((x)=>to_candid_OpeningHours_n20(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
